#!/usr/bin/env ansible-playbook

- hosts: masters
  roles:
    - addYumRepo
    - changeHostName
    - removePackages
    - updateAllPackages
    - installPackages
    - configureHost
    - configureCrio
    - fixHosts
    - rebootHost

- hosts: nodes
  roles:
    - addYumRepo
    - changeHostName
    - removePackages
    - updateAllPackages
    - installPackages
    - configureHost
    - configureCrio
    - fixHosts
    - rebootHost