---
- name: get join command
  shell: kubeadm token create --print-join-command
  register: result
- debug:
    msg:
    - "{{ result }}"

- name: set join command
  set_fact:
    join_command: "{{ result.stdout_lines[0] }}"
# - debug:
#     msg:
#     - "{{ hostvars['192.168.88.2'] }}"

# - name: print ansible facts
#   ansible.builtin.debug:
#     var: ansible_facts
