apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-config
  labels:
    storage-name: lbl-gitlab-config
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.2
    path: "/mnt/sdd1/nfs/gitlab/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-logs
  labels:
    storage-name: lbl-gitlab-logs
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.2
    path: "/mnt/sdd1/nfs/gitlab/config"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pv-data
  labels:
    storage-name: lbl-gitlab-data
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.2
    path: "/mnt/sdd1/nfs/gitlab/data"    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      storage-name: lbl-gitlab-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-logs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      storage-name: lbl-gitlab-logs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      storage-name: lbl-gitlab-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      hostname: gitlab
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        ports:
          - name: gitlab
            containerPort: 8080
        volumeMounts:
            - name: gitlab-pvc-config
              mountPath: "/etc/gitlab"
            - name: gitlab-pvc-logs
              mountPath: "/var/log/gitlab"
            - name: gitlab-pvc-data
              mountPath: "/var/opt/gitlab"
        resources:
          limits:
            cpu: "4"
          requests:
            cpu: "0.5"
      volumes:
      - name: gitlab-pvc-config
        persistentVolumeClaim:
          claimName: gitlab-pvc-config
      - name: gitlab-pvc-logs
        persistentVolumeClaim:
          claimName: gitlab-pvc-logs
      - name: gitlab-pvc-data
        persistentVolumeClaim:
          claimName: gitlab-pvc-data
---
apiVersion: v1
kind: Service
metadata:
  name: "gitlab-svc"
  namespace: "default"
spec:
  ports:
    - port: 80
      nodePort: 30081
  type: NodePort
  selector:
    app: "gitlab"