apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-data
  labels:
    storage-name: lbl-mysql-data
spec:
  capacity:
    storage: 2Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.88.2
    path: "/mnt/sdd1/nfs/mysql/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  selector:
    matchLabels:
      storage-name: lbl-mysql-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysql
      containers:
      - name: mysql
        image: db/mysql:latest
        ports:
          - name: mysqli
            containerPort: 3306
          - name: mysqlii
            containerPort: 33060
          - name: mysqliii
            containerPort: 33061
        volumeMounts:
            - name: mysql-pvc-data
              mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-pvc-data
        persistentVolumeClaim:
          claimName: mysql-pvc-data
---
apiVersion: v1
kind: Service
metadata:
  name: "mysql-svc"
  namespace: "default"
spec:
  ports:
    - port: 3306
      nodePort: 30306
  type: NodePort
  selector:
    app: "mysql"