- include: copyCrioConfigFile.yml
- include: copy99KubernetesCriConfigFile.yml
- include: modifyCrioConf.yml
- include: shellCmdI.yml
- include: copyRegistriesConf.yml
- include: configureDaemon.yml
# - include: installCrio.yml