---
- name: change conmon_cgroups
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^conmon_cgroup\ ='
    line: conmon_cgroup = "pod"
  register: result
- debug:
    msg: "{{ result }}"

- name: change cgroup_manager
  lineinfile:
    path: /etc/crio/crio.conf
    regexp: '^cgroup_manager\ ='
    line: cgroup_manager = "cgroupfs"
  register: result
- debug:
    msg: "{{ result }}"