---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --service-cidr=100.96.0.0/12 --image-repository 192.168.88.2:5005
  ignore_errors: yes
  args:
    chdir: $HOME
  register: result
- debug:
    msg:
    - "{{ result }}"

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
  register: result
- debug:
    msg:
    - "{{ result }}"

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    mode: preserve
  register: result
- debug:
    msg:
    - "{{ result }}"

- name: install Pod network
  shell: kubectl apply -f http://192.168.88.2:8081/repository/raw-kube/spec/kube-flannel.yml
  register: result
- debug:
    msg:
    - "{{ result }}"